#!/bin/bash

#
# Shell script to launch Java app ${config.name}
#
# Auto generated by mfz-jtools-launcher.
#  Web: http://mfizz.com
#  Twitter: http://twitter.com/mfizz_inc
#

#
# settings
#

# min and max mem (in MB); leave empty for java defaults
JAVA_MIN_MEM="${config.minJavaMemory!""}"
JAVA_MAX_MEM="${config.maxJavaMemory!""}"

# min and max mem as a percent of system memory
# they have priority over JAVA_MIN_MEM and JAVA_MAX_MEM if set
JAVA_MIN_MEM_PCT="${config.minJavaMemoryPct!""}"
JAVA_MAX_MEM_PCT="${config.maxJavaMemoryPct!""}"

# dir for run data such as pid file
RUN_DIR="${config.runDir!""}"

#
# constants
#

NAME="${config.name}"
TYPE="${config.type}"
MAIN_CLASS="${config.mainClass}"
WORKING_DIR_MODE="${config.workingDirMode}"
APP_ARGS="${config.appArgs}"
JAVA_ARGS="${config.javaArgs}"
JAR_DIR="${config.jarDir}"
MIN_JAVA_VERSION="${config.minJavaVersion}"

#
# working directory
#

# save current working directory
INITIAL_WORKING_DIR="`pwd`"

# change working directory to app home
cd $(dirname $0)/..

# application home is now current directory
APP_HOME="`pwd`"

# revert to initial working directory?
if [ $WORKING_DIR_MODE == "RETAIN" ]; then
  cd "$INITIAL_WORKING_DIR"
fi

#
# is run directory absolute or relative to app home?
#
if [[ "$RUN_DIR" == /* ]]; then
    # absolute path
    APP_RUN_DIR="$RUN_DIR"
else
    # relative path to app home
    APP_RUN_DIR="$APP_HOME/$RUN_DIR"
fi

#
# pid handling
#
APP_PID_FILE="$APP_RUN_DIR/$NAME.pid"

# will a pid file be used?
if [ "$TYPE" == "DAEMON" ]; then
    if [ ! -d $APP_RUN_DIR ]; then 
        mkdir -p "$APP_RUN_DIR"
    fi
    if [ ! -w $APP_RUN_DIR ]; then
        echo "Error: run directory is not writable by app! [run_dir=$APP_RUN_DIR]"
        exit 1
    fi
fi