#!/usr/bin/env sh

#
# Shell script to detect Java installed
#
# Auto generated by mfz-jtools-launcher.
#  Web: http://mfizz.com
#  Twitter: http://twitter.com/mfizz_inc
#

[ -z $LAUNCHER_DEBUG ] && LAUNCHER_DEBUG="0"
