#!/bin/bash

#
# Shell script to launch Java app ${config.name}
#
# Auto generated by mfz-jtools-launcher.
#  Web: http://mfizz.com
#  Twitter: http://twitter.com/mfizz_inc
#

#
# settings
#

# min and max mem (in MB); leave empty for java defaults
JAVA_MIN_MEM=
JAVA_MAX_MEM=

# min and max mem as a percent of system memory
# they have priority over JAVA_MIN_MEM and JAVA_MAX_MEM if set
JAVA_MIN_MEM_PCT=
JAVA_MAX_MEM_PCT=

#
# constants
#

NAME="${config.name}"
TYPE="${config.type}"
MAIN_CLASS="${config.mainClass}"
WORKING_DIR_MODE="${config.workingDirMode}"
APP_ARGS="${config.appArgs}"
JAVA_ARGS="${config.javaArgs}"
JAR_DIR="${config.jarDir}"
MIN_JAVA_VERSION="${config.minJavaVersion}"

# directory for pid file (relative dirs to app home)
# RUN_DIR="$RUN_DIR"

# directory for init.d script for daemons
#INITD_DIR="$INITD_DIR"

# single instance ony permitted of app?
# only applies to console apps as daemons will always only allow single instances
#SINGLE_INSTANCE=$SINGLE_INSTANCE


#
# working directory
#

# save current working directory
INITIAL_WORKING_DIR="`pwd`"

# change working directory to app home
cd $(dirname $0)/..

# application home is now current directory
APP_HOME="`pwd`"

# revert to initial working directory?
if [ $WORKING_DIR_MODE == "RETAIN" ]; then
  cd "$INITIAL_WORKING_DIR"
fi
