server:
	mvn -e compile exec:java -Dexec.classpathScope="compile" -Dexec.mainClass="co.fizzed.stork.examples.helloserver.HelloServer" -Dexec.args="server conf/hello-server.yml"

assembly:
	mvn clean assembly:assembly