@setlocal ENABLEDELAYEDEXPANSION
@echo OFF

@REM
@REM Batch script to launch Java app ${config.name}
@REM
@REM Description: ${config.shortDescription}
@REM
@REM Auto generated by mfz-jtools-launcher.
@REM  Web: http://mfizz.com
@REM  Twitter: http://twitter.com/mfizz_inc
@REM

@REM
@REM settings
@REM

set LOG_DIR=${config.logDir!""}
set RUN_DIR=${config.runDir!""}

@REM
@REM constants
@REM

set NAME=${config.name}
set TYPE=${config.type}
set MAIN_CLASS=${config.mainClass}
set MIN_JAVA_VERSION=${config.minJavaVersion}
set WORKING_DIR_MODE=${config.workingDirMode}
set BIN_DIR=${config.binDir!""}
set LIB_DIR=${config.libDir!""}

@REM
@REM working directories
@REM

set INITIAL_WORKING_DIR=%CD%
set APP_HOME_REL=%~dp0..

@REM do we need to change the current working directory?
if %WORKING_DIR_MODE%==APP_HOME (
    pushd %APP_HOME_REL%
    set APP_HOME=.
) else (
    @REM temporarily change working directory to get good abs path
    pushd %APP_HOME_REL%
    set APP_HOME=%CD%
    rem popd
)

@REM setup remaining directories
set APP_BIN_DIR=%APP_HOME%\%BIN_DIR%
set APP_LOG_DIR=%APP_HOME%\%LOG_DIR%
set APP_LIB_DIR=%APP_HOME%\%LIB_DIR%
set APP_RUN_DIR=%APP_HOME%\%RUN_DIR%

if "%VERBOSE%"=="1" (
    echo working_dir: %CD%
    echo app_home: %APP_HOME%
    echo app_bin: %APP_BIN_DIR%
    echo app_log: %APP_LOG_DIR%
    echo app_lib: %APP_LIB_DIR%
    echo app_run: %APP_RUN_DIR%
)

@REM echo Relative home: !APP_HOME:%CD%\=!

@REM
@REM usage with no parameters?
@REM

IF %1.==. GOTO PrintUsage


set bit64=n
if /I %Processor_Architecture%==AMD64 set bit64=y
if /I "%PROCESSOR_ARCHITEW6432%"=="AMD64" set bit64=y

REM echo bit64: %bit64%



REM
REM log directory MUST exist for service to start correctly
REM

REM
REM execute argument command
REM

if %bit64%==n set TargetExe=hello-daemon32.exe
if %bit64%==y set TargetExe=hello-daemon64.exe

IF %1==-run (
	"%BIN_HOME%\%TargetExe%" -debug
) ELSE IF %1==-start (
	net start Hello Server
) ELSE IF %1==-stop (
	net stop Hello Server
) ELSE IF %1==-install (
	"%BIN_HOME%\%TargetExe%" -install
) ELSE IF %1==-uninstall (
	"%BIN_HOME%\%TargetExe%" -remove
) ELSE (
	echo Error unsupported argument
	GOTO PrintUsage
)

GOTO endLabel

:PrintUsage
REM annoying string escaping
echo Usage: ^[-run^|-^s^t^a^r^t^|-^s^t^o^p^|^-^ins^tall^|^-^un^inst^a^ll^]
exit /b
GOTO endLabel

:endLabel